#!/bin/sh

# chkconfig: 345 99 10
# description: apache tomcat auto start-stop script.

. /etc/init.d/functions

RETVAL=0

start()
{
  su - tomcat -c "/opt/apache/tomcat/current/bin/startup.sh" #> /dev/null 
  sleep 1
  echo -n "Starting tomcat"
  ps -eo command | grep tomcat | grep -v "tomcat start" | grep -v grep > /dev/null
  if [ $? -eq 0 ]; then
  	success
  else
	failure
  fi
  echo
}

stop()
{
  su - tomcat -c "/opt/apache/tomcat/current/bin/shutdown.sh" #> /dev/null
  sleep 1
  echo -n "Stopping tomcat"
  ps -eo command | grep tomcat | grep -v "tomcat stop" | grep -v grep > /dev/null
  if [ $? -eq 1 ]; then
        success
  else
        failure
  fi
  echo
}

status()
{
  ps -eo command | grep tomcat | grep -v "tomcat status" | grep -v grep > /dev/null
  if [ $? -eq 0 ]; then
	echo 'tomcat is running '$(success)
  else
	echo 'tomcat is not running '$(failure)
  fi
}

case "$1" in
start)
        start
        ;;
stop)
        stop
        ;;
status)
        status
        ;;
restart)
        stop
        start
        ;;
*)
        echo "Usage: $0 {start|stop|status|restart}"
        exit 1
esac

