#!/bin/sh

# chkconfig: 345 99 10
# description: apache tomcat auto start-stop script.

. /etc/init.d/functions

RETVAL=0

start()
{
  echo -n "Starting tomcat"
  su - tomcat -c "/opt/apache/tomcat/current/bin/startup.sh" 
  if [ $? -eq 0 ];then  
  	success
  else
	failure
  fi
  echo
}

stop()
{
  echo -n "Stopping tomcat"
  su - tomcat -c "/opt/apache/tomcat/current/bin/shutdown.sh"
  if [ $? -eq 0 ];then
        success
  else
        failure
  fi
  echo
}

status()
{
  ps aux | grep java | grep -v grep > /dev/null
  if [ $? -eq 0 ]; then
	echo 'tomcat is running'
  else
	echo 'tomcat is not running'
  fi
}

case "$1" in
start)
        start
        ;;
stop)
        stop
        ;;
status)
        status
        ;;
restart)
        stop
        start
        ;;
*)
        echo "Usage: $0 {start|stop|status|restart}"
        exit 1
esac

